[installation]
default_target = "~/.agents/skills"

[machines.fht]

[repositories.obsidian]
path = "external/kepano/obsidian-skills"
url = "https://github.com/kepano/obsidian-skills.git"

[repositories.mattpocock]
path = "external/mattpocock/skills"
url = "https://github.com/mattpocock/skills.git"

[repositories.marimo]
path = "external/marimo-team/skills"
url = "https://github.com/marimo-team/skills.git"

[repositories.marimo-pair]
path = "external/marimo-team/marimo-pair"
url = "https://github.com/marimo-team/marimo-pair.git"

#[repositories.scientific]
#path = "external/kdense/claude-scientific-skills"
#url = "https://github.com/K-Dense-AI/claude-scientific-skills.git"

#[repositories.anthropic]
#path = "external/anthropic-skills"
#url = "https://github.com/anthropics/skills.git"

[[skills.skill]]
name = "defuddle"
repo = "external/kepano/obsidian-skills/skills/defuddle"
enabled = true

[[skills.skill]]
name = "obsidian-bases"
repo = "external/kepano/obsidian-skills/skills/obsidian-bases"
enabled = true

[[skills.skill]]
name = "obsidian-cli"
repo = "external/kepano/obsidian-skills/skills/obsidian-cli"
enabled = true

[[skills.skill]]
name = "obsidian-markdown"
repo = "external/kepano/obsidian-skills/skills/obsidian-markdown"
enabled = true

[[skills.skill]]
name = "grill-me"
repo = "external/mattpocock/skills/skills/productivity/grill-me"
enabled = true

[[skills.skill]]
name = "grilling"
repo = "external/mattpocock/skills/skills/productivity/grilling"
enabled = true

[[skills.skill]]
name = "teach"
repo = "external/mattpocock/skills/skills/productivity/teach"
enabled = true

[[skills.skill]]
name = "handoff"
repo = "external/mattpocock/skills/skills/productivity/handoff"
enabled = true

[[skills.skill]]
name = "marimo-notebook"
repo = "external/marimo-team/skills/skills/marimo-notebook"
enabled = true

[[skills.skill]]
name = "marimo-pair"
repo = "external/marimo-team/marimo-pair/skills/marimo-pair"
enabled = true

[[skills.skill]]
name = "ics-extractor"
repo = "dmp-skills/ics-extractor"
enabled = true

[[skills.skill]]
name = "justfile-builder"
repo = "dmp-skills/justfile-builder"
enabled = true

[[skills.skill]]
name = "gprofiler-gost"
repo = "dmp-skills/gprofiler-gost"
enabled = true

[[skills.skill]]
name = "add-external-skill-repo"
repo = "dmp-skills/add-external-skill-repo"
enabled = true
install_targets = { fht = "./.codex" }

[[skills.skill]]
name = "academic-research-grill"
repo = "dmp-skills/academic-research-grill"
enabled = true

[[skills.skill]]
name = "ggplot-data-visualization"
repo = "dmp-skills/ggplot-data-visualization"
enabled = true

[update]
exclude = [
]
